import 'package:flutter/material.dart';

/* Text NEXT PAGE
    Autogenerated by FlutLab FTF Generator
  */
class NEXTPAGEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefined53eb'),
      child: Text(
        '''NEXT PAGE''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.left,
        style: TextStyle(
          height: 1.171875,
          fontSize: 30.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w400,
          color: Color.fromARGB(255, 0, 0, 0),
          /* letterSpacing: 0.0, */
        ),
      ),
    );
  }
}
