import 'package:flutter/material.dart';

/* Rectangle Rectangle 1
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(33.0),
      child: Container(
        width: 414.0,
        height: 429.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(33.0),
          image: DecorationImage(
            image: ExactAssetImage(
              "assets/images/ce94e55a7f6f0d18258bbcf9a09c2c8ecd6fe3b5.png",
            ),
            fit: BoxFit.cover,
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(33.0),
          child: Image.asset(
            "assets/images/ce94e55a7f6f0d18258bbcf9a09c2c8ecd6fe3b5.png",
            color: null,
            fit: BoxFit.cover,
            width: 414.0,
            height: 429.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
