import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/GroupWidget.dart';

/* Frame emojione-v1:back-arrow
    Autogenerated by FlutLab FTF Generator
  */
class Emojionev1backarrowWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Main_pageWidget'),
      child: Container(
        width: 64.0,
        height: 64.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double width = constraints.maxWidth * 1.0015780925750732;

                    double height = constraints.maxHeight * 0.637499988079071;

                    return Stack(children: [
                      Transform(
                        transform: Matrix4(
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            constraints.maxWidth * -0.0006093750125728548,
                            constraints.maxHeight * 0.17351561784744263,
                            0,
                            1),
                        alignment: Alignment.topLeft,
                        child: Container(
                          width: width,
                          height: height,
                          child: GroupWidget(),
                        ),
                      )
                    ]);
                  }),
                )
              ]),
        ),
      ),
    );
  }
}
