import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/Rectangle5Widget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class Frame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 142.0,
      height: 57.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 10.0,
            top: 10.0,
            right: null,
            bottom: null,
            width: 122.0,
            height: 37.0,
            child: Rectangle5Widget(),
          )
        ]),
      ),
    );
  }
}
