import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/VectorWidget.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/VectorWidget4.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/VectorWidget1.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/VectorWidget3.dart';
import 'package:flutterapp/figma/undefined53eb/widgets/VectorWidget2.dart';

/* Group Group
    Autogenerated by FlutLab FTF Generator
  */
class GroupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 64.10099792480469,
      height: 40.79999923706055,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.9375989514685226;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 60.10102844238281;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.5721569168269759;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 23.34400177001953;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.20901390301607528;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 13.39799976348877;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.3552205956257202;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 14.493000030517578;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.0342740378126426,
                      constraints.maxHeight * 0.638602960597823,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget1(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.24612722013709845;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 15.777000427246094;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.3552205956257202;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 14.493000030517578;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.2517433371190093,
                      constraints.maxHeight * 0.6386274569385652,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget2(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.2199029832253531;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 14.096000671386719;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.36730392993298566;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 14.986000061035156;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.5062167885486119,
                      constraints.maxHeight * 0.6326960700670143,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget3(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.23960621272991672;
              double scaleX =
                  (constraints.maxWidth * percentWidth) / 15.358997344970703;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.3552450919664625;
              double scaleY =
                  (constraints.maxHeight * percentHeight) / 14.493999481201172;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.7603937872700832,
                      constraints.maxHeight * 0.6385784642570806,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: VectorWidget4(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
