import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.777000427246094,
      height: 14.493000030517578,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M10.364 12.099L5.279 12.099L4.572 14.493L0 14.493L5.448 0L10.333 0L15.777 14.493L11.089 14.493L10.364 12.099L10.364 12.099ZM9.434 8.967L7.835 3.759L6.253 8.967L9.434 8.967Z')
          ..color = Color.fromARGB(255, 64, 88, 102),
      ]),
    );
  }
}
