import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.358997344970703,
      height: 14.493999481201172,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0 0.000999451L4.477 0.000999451L4.477 5.479L9.166 0.000999451L15.123 0.000999451L9.834 5.474L15.359 14.494L9.842 14.494L6.789 8.534L4.477 10.957L4.477 14.493L0 14.493L0 0')
          ..color = Color.fromARGB(255, 64, 88, 102),
      ]),
    );
  }
}
