import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */
class VectorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 60.10102844238281,
      height: 23.34400177001953,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M13.867 23.344L0 11.7L13.737 0C15.66 0.137 17.179 1.39 17.186 2.92L17.197 5.524L56.237 5.454C58.343 5.443 60.064 7.1 60.075 9.161L60.101 13.985C60.109 16.043 58.41 17.708 56.304 17.719L17.264 17.785L17.277 20.385C17.288 21.914 15.793 23.183 13.869 23.344')
          ..color = Color.fromARGB(255, 64, 88, 102),
      ]),
    );
  }
}
