import 'package:flutter/material.dart';

/* Text WELCOME TO the Next Page
    Autogenerated by FlutLab FTF Generator
  */
class WELCOMETOtheNextPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''WELCOME TO the Next Page''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 30.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
